import { buildInternalLinkHref } from "./internalLinks";
import { CIRCLE_SEATING_SVG, DAY_TIMELINE_SVG, ESCALATION_LADDER_SVG } from "./seedFigures";
import { buildMigratedMaterialId, slugify } from "./slug";
import type {
  CardColor,
  EditorJsBlock,
  EditorJsOutputData,
  FileExt,
  MacroCategory,
  MaterialType,
  MaterialVideo,
  SectionLayout,
} from "./types";

// Demo content for the public build: a staff handbook of a fictional
// rehabilitation centre. Everything here is written for the demo — no real
// organisation, person or protocol is reproduced. The point is to exercise
// every feature of the product on material that looks like the real job:
// shift work, paper forms, crisis protocols, group sessions.

export function eBlockHeader(text: string, level = 2): EditorJsBlock {
  return { type: "header", data: { text, level } };
}
export function eBlockParagraph(text: string): EditorJsBlock {
  return { type: "paragraph", data: { text } };
}
export function eBlockQuote(text: string, caption = ""): EditorJsBlock {
  return { type: "quote", data: { text, caption } };
}
export function eBlockAlert(kind: "warning" | "danger", text: string): EditorJsBlock {
  return { type: "alert", data: { type: kind, align: "left", text } };
}
export function eBlockList(
  style: "ordered" | "unordered" | "checklist",
  items: Array<{ content: string; items?: Array<{ content: string }> }>,
): EditorJsBlock {
  return {
    type: "list",
    data: {
      style,
      meta: style === "ordered" ? { counterType: "numeric", start: 1 } : {},
      items: items.map((item) => ({
        content: item.content,
        meta: style === "checklist" ? { checked: false } : {},
        items: (item.items ?? []).map((sub) => ({
          content: sub.content,
          meta: style === "checklist" ? { checked: false } : {},
          items: [],
        })),
      })),
    },
  };
}
export function eBlockTable(withHeadings: boolean, content: string[][]): EditorJsBlock {
  return { type: "table", data: { withHeadings, content } };
}
export function eBlockImage(key: string, caption: string): EditorJsBlock {
  return { type: "image", data: { file: { key }, caption } };
}

export function buildOutputData(blocks: EditorJsBlock[]): EditorJsOutputData {
  return { time: Date.parse("2026-07-26T00:00:00Z"), blocks, version: "2.31.0" };
}

/** The id a seeded material will get — used to link materials to each other. */
export function seedMaterialId(type: MaterialType, sectionSlug: string, nameSlugSource: string): string {
  return buildMigratedMaterialId(type, sectionSlug, slugify(nameSlugSource));
}

/** Inline cross-link to another material, the same markup the editor produces. */
function link(type: MaterialType, sectionSlug: string, nameSlugSource: string, text: string): string {
  return `<a href="${buildInternalLinkHref(seedMaterialId(type, sectionSlug, nameSlugSource))}">${text}</a>`;
}

/**
 * Demo training clips generated by scripts/make_demo_clips.mjs; durations come
 * from its report. The poster lands on the fully drawn title slide.
 */
function clip(file: string, durationSec: number): MaterialVideo {
  return { path: file, durationSec, width: 1280, height: 720, posterFrameSec: 2 };
}

export interface SeedSectionSpec {
  slug: string;
  title: string;
  description: string;
  macroCategory: MacroCategory;
  parentSlug: string | null;
  layout: SectionLayout;
  order: number;
  primaryTag: string;
}

export const seedSections: SeedSectionSpec[] = [
  {
    slug: "intake",
    title: "Intake and first days",
    description: "Admitting a new resident: paperwork, the first conversation, the first night.",
    macroCategory: "instructions",
    parentSlug: null,
    layout: "grid",
    order: 1,
    primaryTag: "intake",
  },
  {
    slug: "programme",
    title: "Daily programme",
    description: "The shape of an ordinary day and how staff hold it together.",
    macroCategory: "methods",
    parentSlug: null,
    layout: "list",
    order: 2,
    primaryTag: "programme",
  },
  {
    slug: "night-shift",
    title: "Night shift",
    description: "The quiet hours: rounds, sleep, and what counts as waking the lead.",
    macroCategory: "methods",
    parentSlug: "programme",
    layout: "list",
    order: 1,
    primaryTag: "night",
  },
  {
    slug: "film-therapy",
    title: "Film therapy",
    description: "Film sessions: what to show, what to ask afterwards.",
    macroCategory: "methods",
    parentSlug: null,
    layout: "carousel",
    order: 3,
    primaryTag: "therapy",
  },
  {
    slug: "group-work",
    title: "Group work",
    description: "Check-ins, thematic groups, and what to do when the room goes quiet.",
    macroCategory: "methods",
    parentSlug: null,
    layout: "list",
    order: 4,
    primaryTag: "therapy",
  },
  {
    slug: "families",
    title: "Working with families",
    description: "Calls, visits, and the boundaries that keep everyone safe.",
    macroCategory: "methods",
    parentSlug: null,
    layout: "list",
    order: 5,
    primaryTag: "communication",
  },
  {
    slug: "crisis",
    title: "Crisis situations",
    description: "Rare, loud, and no time to read: the first three minutes of each.",
    macroCategory: "instructions",
    parentSlug: null,
    layout: "list",
    order: 4,
    primaryTag: "crisis",
  },
  {
    slug: "records",
    title: "Journals and forms",
    description: "What gets written down, on which sheet, and who signs it.",
    macroCategory: "formal",
    parentSlug: null,
    layout: "list",
    order: 5,
    primaryTag: "documents",
  },
  {
    slug: "house-rules",
    title: "House rules",
    description: "The rules residents agree to, and the limits staff work within.",
    macroCategory: "formal",
    parentSlug: null,
    layout: "list",
    order: 6,
    primaryTag: "regulations",
  },
  {
    slug: "aftercare",
    title: "Aftercare",
    description: "Transitional housing, check-ins, and the first month back at work.",
    macroCategory: "other",
    parentSlug: null,
    layout: "grid",
    order: 7,
    primaryTag: "aftercare",
  },
];

export interface SeedArticleSpec {
  type: "article";
  nameSlugSource: string;
  title: string;
  sectionSlug: string;
  order: number;
  cardColor: CardColor;
  tags?: string[];
  video?: MaterialVideo;
  /** Inline SVG diagrams, keyed by attachment name; referenced via eBlockImage. */
  figures?: Record<string, string>;
  blocks: EditorJsBlock[];
}

export interface SeedFileSpec {
  type: "form" | "presentation";
  nameSlugSource: string;
  title: string;
  sectionSlug: string;
  order: number;
  cardColor: CardColor;
  tags?: string[];
  fileExt: FileExt;
  fileSizeOriginal: number;
  fileSizePdf: number;
  /** Lines printed on the blank: they reach both the PDF and the search index. */
  fileLines?: string[];
}

export interface SeedFilmSpec {
  type: "film";
  nameSlugSource: string;
  title: string;
  sectionSlug: string;
  order: number;
  cardColor: CardColor;
  tags?: string[];
  video?: MaterialVideo;
  introBlocks: EditorJsBlock[];
  questionsBlocks: EditorJsBlock[];
}

export type SeedMaterialSpec = SeedArticleSpec | SeedFileSpec | SeedFilmSpec;

export const seedMaterials: SeedMaterialSpec[] = [
  // --- Intake and first days ------------------------------------------------
  {
    type: "article",
    nameSlugSource: "The first twenty-four hours",
    title: "The first twenty-four hours",
    sectionSlug: "intake",
    order: 1,
    cardColor: "green",
    tags: ["intake", "communication"],
    blocks: [
      eBlockParagraph(
        "The first day decides how much of the programme a person will accept. Nothing here is therapy yet: it is paperwork, a bed, food, and one adult who is clearly in charge and clearly calm.",
      ),
      eBlockHeader("Order of the day", 2),
      eBlockList("checklist", [
        { content: "Meet at the door, take the bag, sit down somewhere quiet" },
        { content: "Explain what will happen in the next two hours, in that order" },
        { content: "Belongings inventory, signed by both of you" },
        { content: "Show the bed, the bathroom, where water is" },
        { content: "Feed the person before any long conversation" },
        { content: "Intake interview, unhurried" },
        { content: "Introduce one resident who will answer questions today" },
      ]),
      eBlockAlert(
        "warning",
        "Do not start with rules. A person who has just arrived remembers tone, not clauses — the rules are read together on day two.",
      ),
      eBlockHeader("The first hour, minute by minute", 3),
      eBlockTable(true, [
        ["When", "What happens", "Who"],
        ["0–10 min", "Door, bag, a seat somewhere quiet, water", "Duty consultant"],
        ["10–25 min", "What happens next, said once, slowly", "Duty consultant"],
        ["25–40 min", "Belongings inventory, both signatures", "Consultant + newcomer"],
        ["40–50 min", "Bed, bathroom, where things are", "Senior resident"],
        ["50–60 min", "Food, even between meals", "Kitchen duty"],
      ]),
      eBlockParagraph(
        `The questions themselves are in ${link("article", "intake", "The intake interview", "The intake interview")}, and the sheet you fill in is ${link("form", "intake", "Intake checklist", "the intake checklist")}.`,
      ),
      eBlockHeader("The first night", 2),
      eBlockParagraph(
        "Warn the night shift by name, not with the word “newcomer” in the log. The first night is when leaving feels most reasonable: the adrenaline of the decision has worn off and nothing has replaced it yet. The night consultant looks in a little more often, without making a ceremony of it, and knows where the person's file is in case the conversation from " +
          `${link("article", "crisis", "A resident wants to leave", "A resident wants to leave")} happens at two in the morning.`,
      ),
      eBlockHeader("What counts as a bad first day", 3),
      eBlockList("unordered", [
        { content: "The newcomer heard four different versions of the schedule" },
        { content: "Nobody wrote down what was in the bag" },
        {
          content: "The first conversation happened while the consultant was doing something else",
          items: [{ content: "answering the phone" }, { content: "handing out chores" }],
        },
      ]),
    ],
  },
  {
    type: "article",
    nameSlugSource: "The intake interview",
    title: "The intake interview",
    sectionSlug: "intake",
    order: 2,
    cardColor: "blue",
    tags: ["intake", "communication"],
    blocks: [
      eBlockParagraph(
        "One conversation, thirty to forty minutes, no clipboard between you. Write afterwards, not during — a person watching you take notes edits themselves.",
      ),
      eBlockHeader("What you need to leave with", 2),
      eBlockList("ordered", [
        { content: "Who to call, and who must not be called" },
        { content: "Sleep and food: what the last week actually looked like" },
        { content: "Anything the person is carrying that staff must know about" },
        { content: "What they think they are here for — in their words, written down verbatim" },
        { content: "One thing that would make the first night easier" },
      ]),
      eBlockQuote(
        "The first interview is not an assessment. It is the moment a person decides whether it is safe to tell you the truth later.",
        "Staff handbook",
      ),
      eBlockAlert(
        "warning",
        "If the person cannot hold a conversation — exhausted, frightened, unwell — stop and let them sleep. The interview keeps until morning; trust does not survive being pushed.",
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Naming feelings",
    title: "Naming feelings",
    sectionSlug: "intake",
    order: 3,
    cardColor: "purple",
    tags: ["therapy", "intake"],
    blocks: [
      eBlockParagraph(
        "Most people arrive with three words for everything they feel: fine, angry, tired. Widening that vocabulary is not a nicety — it is what makes the journals worth reading later.",
      ),
      eBlockHeader("How the table is used", 2),
      eBlockList("unordered", [
        { content: "In the first week, one feeling a day, named out loud at the evening review" },
        { content: "Later, paired with the situation that produced it" },
        { content: "Never as a test: there is no wrong square" },
      ]),
      eBlockParagraph(
        "The printable table below fits one sheet. Print it for the folder rather than copying it by hand.",
      ),
    ],
  },
  {
    type: "form",
    nameSlugSource: "Intake checklist",
    title: "Intake checklist",
    sectionSlug: "intake",
    order: 4,
    cardColor: "neutral",
    tags: ["documents", "intake"],
    fileExt: "docx",
    fileSizeOriginal: 41_000,
    fileSizePdf: 96_000,
    fileLines: [
      "Resident name / date and time of arrival",
      "Belongings inventory attached: yes / no",
      "Emergency contact, relationship, phone",
      "Anyone who must not be contacted",
      "Bed and room assigned",
      "House agreement read together: yes / no",
      "Consultant on duty (signature)",
    ],
  },
  {
    type: "form",
    nameSlugSource: "House agreement",
    title: "House agreement",
    sectionSlug: "intake",
    order: 5,
    cardColor: "neutral",
    tags: ["documents", "regulations"],
    fileExt: "pdf",
    fileSizeOriginal: 88_000,
    fileSizePdf: 88_000,
    fileLines: [
      "I agree to follow the house rules while I live here.",
      "Nothing that alters my state comes through the door.",
      "No violence and no threats, in any direction.",
      "I attend the morning circle, meals and group sessions.",
      "I do the duties listed on the rota for my name.",
      "Phones and visits follow the posted schedule.",
      "Signature and date",
    ],
  },
  {
    type: "presentation",
    nameSlugSource: "Orientation for new residents",
    title: "Orientation for new residents",
    sectionSlug: "intake",
    order: 6,
    cardColor: "pink",
    tags: ["intake", "programme"],
    fileExt: "pptx",
    fileSizeOriginal: 1_240_000,
    fileSizePdf: 420_000,
    fileLines: [
      "Welcome: how the first week works",
      "The day: circle, chores, meals, group, evening review",
      "House rules in one page",
      "Calls and visits: the posted schedule",
      "Who to ask when something is unclear",
    ],
  },

  // --- Daily programme ------------------------------------------------------
  {
    type: "article",
    nameSlugSource: "The rhythm of the day",
    title: "The rhythm of the day",
    sectionSlug: "programme",
    order: 1,
    cardColor: "blue",
    tags: ["programme"],
    figures: { "day-timeline": DAY_TIMELINE_SVG },
    blocks: [
      eBlockParagraph(
        "Structure is not a side effect of the programme — it is the programme. Most people arrive from months or years in which days had no shape at all: sleep at random hours, meals when they happened, nothing that had to be done at a fixed time. A day with a spine is the first therapeutic intervention, before a single group has been run.",
      ),
      eBlockImage("day-timeline", "Fixed points hold the day; the rest can flex around them."),
      eBlockHeader("Three kinds of time", 2),
      eBlockList("unordered", [
        {
          content: "<b>Fixed points</b> — the morning circle, meals, the evening review, lights out. They happen at the same minute every day, and staff defend them even when it is inconvenient",
        },
        {
          content: "<b>Protected time</b> — the quiet hour and group sessions. Nothing interrupts them: no phone calls, no visitors, no chores that suddenly became urgent",
        },
        {
          content: "<b>Flexible time</b> — chores, walks, personal tasks. This is where plans may shift, and where residents practise deciding for themselves inside a frame that holds",
        },
      ]),
      eBlockHeader("Why staff never trade the fixed points away", 3),
      eBlockParagraph(
        "Every skipped circle and every delayed lights-out sends the same message: the structure bends if you push it. For someone relearning to trust their own commitments, that message is expensive. The rule of thumb: the schedule can be renegotiated at the weekly house meeting, never in the moment.",
      ),
      eBlockQuote(
        "The day holds the person until the person can hold the day.",
        "Staff handbook",
      ),
      eBlockParagraph(
        `The two anchors of the day are described in detail in ${link("article", "programme", "Opening the morning circle", "Opening the morning circle")} and ${link("article", "programme", "Closing the day", "Closing the day")}; the night half belongs to ${link("article", "night-shift", "The quiet hours", "The quiet hours")}.`,
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Opening the morning circle",
    title: "Opening the morning circle",
    sectionSlug: "programme",
    order: 2,
    cardColor: "green",
    tags: ["programme", "therapy"],
    video: clip("opening-the-morning-circle.mp4", 22.52),
    figures: { "circle-seating": CIRCLE_SEATING_SVG },
    blocks: [
      eBlockParagraph(
        "The circle sets the temperature of the whole day. It is short on purpose: twenty minutes, everyone seated, nobody standing over anyone.",
      ),
      eBlockHeader("The shape of it", 2),
      eBlockList("ordered", [
        { content: "One sentence each: how the night went" },
        { content: "Today's plan, read once, from the board" },
        { content: "Chores confirmed out loud, not assumed" },
        { content: "One question anybody may ask about the day" },
      ]),
      eBlockHeader("The room matters more than it looks", 3),
      eBlockImage("circle-seating", "One ring, no second row: geometry does half the facilitator's work."),
      eBlockParagraph(
        "A second row of chairs quietly creates an audience, and an audience changes what people are willing to say. Before anyone sits down, make the ring big enough for everybody — including the person you suspect will try to stand by the wall.",
      ),
      eBlockHeader("When someone refuses to speak", 3),
      eBlockParagraph(
        "Passing is allowed and free — say so at the start, every time. A person who passes three mornings in a row is not a discipline problem; they are a conversation the consultant needs to have privately, after breakfast, without the word “circle” in the first sentence.",
      ),
      eBlockAlert(
        "warning",
        "The circle is not the place to raise a conflict between two people. Note it, close the circle on time, deal with it after — see the crisis protocols.",
      ),
      eBlockParagraph(
        `Chores are allocated by the rota described in ${link("article", "programme", "The chores rota", "The chores rota")}. The evening counterpart of this meeting is ${link("article", "programme", "Closing the day", "Closing the day")}.`,
      ),
      eBlockQuote("A circle that starts late teaches that nothing here starts on time.", "Staff handbook"),
    ],
  },
  {
    type: "article",
    nameSlugSource: "The chores rota",
    title: "The chores rota",
    sectionSlug: "programme",
    order: 3,
    cardColor: "blue",
    tags: ["chores", "programme"],
    blocks: [
      eBlockParagraph(
        "Chores are not punishment and not therapy. They are the ordinary work of living together, and the rota exists so that nobody has to argue about fairness every morning.",
      ),
      eBlockHeader("This week", 2),
      eBlockTable(true, [
        ["Duty", "Morning", "Evening", "Checked by"],
        ["Kitchen", "Two people", "Two people", "Duty consultant"],
        ["Common room", "One person", "One person", "Duty consultant"],
        ["Yard", "One person", "—", "Senior resident"],
        ["Laundry", "—", "One person", "Duty consultant"],
      ]),
      eBlockList("unordered", [
        { content: "Rotation is weekly, posted on the board on Sunday evening" },
        { content: "Swaps are allowed if both people tell the duty consultant before the circle" },
        { content: "Nobody keeps the same heavy duty two weeks running" },
      ]),
      eBlockAlert(
        "warning",
        "A chore taken away as a penalty stops being a shared duty and becomes leverage. Penalties are handled through the house rules, not the rota.",
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Journaling groups",
    title: "Journaling groups",
    sectionSlug: "programme",
    order: 4,
    cardColor: "purple",
    tags: ["therapy", "documents"],
    blocks: [
      eBlockParagraph(
        "Residents write daily; twice a week the group reads aloud. The consultant's job in that hour is almost entirely restraint.",
      ),
      eBlockHeader("Rules of the reading", 2),
      eBlockList("checklist", [
        { content: "The author reads their own entry, or passes — passing is free" },
        { content: "No advice from the group unless the author asks for it" },
        { content: "No comparisons between people's entries" },
        { content: "What is read in the group stays in the group" },
      ]),
      eBlockParagraph(
        `Blank pages and the daily sheet are in ${link("form", "records", "Daily journal page", "Daily journal page")}.`,
      ),
      eBlockAlert(
        "danger",
        "If an entry describes harm to the person or to someone else, the group stops being the right place. Close the session normally, then follow the crisis protocol without delay.",
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Meal quality check",
    title: "Meal quality check",
    sectionSlug: "programme",
    order: 5,
    cardColor: "green",
    tags: ["chores", "documents"],
    video: clip("meal-quality-check.mp4", 22.52),
    blocks: [
      eBlockParagraph(
        "Someone tastes every meal before it is served, writes one line, and signs it. It takes two minutes and settles most arguments about food before they start.",
      ),
      eBlockList("checklist", [
        { content: "Taste from the pot, not from a plate prepared for you" },
        { content: "Temperature: hot food hot, cold food cold" },
        { content: "Portion size against the number of people at the table" },
        { content: "One line in the register, signed" },
      ]),
      eBlockParagraph(
        `The register itself is ${link("form", "records", "Food quality register", "Food quality register")}.`,
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Closing the day",
    title: "Closing the day",
    sectionSlug: "programme",
    order: 6,
    cardColor: "pink",
    tags: ["programme", "communication"],
    blocks: [
      eBlockParagraph(
        "The evening review is where the day is filed away. Fifteen minutes, same seats as the morning, and the consultant speaks last.",
      ),
      eBlockList("ordered", [
        { content: "What went well today — one thing each, no elaboration required" },
        { content: "What was hard — same rule" },
        { content: "Anything unfinished that the night shift must know" },
        { content: "Tomorrow in one sentence" },
      ]),
      eBlockParagraph(
        `Everything in point three goes into the handover — see ${link("article", "night-shift", "Handover between shifts", "Handover between shifts")}.`,
      ),
    ],
  },

  // --- Night shift ----------------------------------------------------------
  {
    type: "article",
    nameSlugSource: "The quiet hours",
    title: "The quiet hours",
    sectionSlug: "night-shift",
    order: 1,
    cardColor: "blue",
    tags: ["night", "programme"],
    video: clip("night-rounds.mp4", 22.52),
    figures: { "escalation-ladder": ESCALATION_LADDER_SVG },
    blocks: [
      eBlockParagraph(
        "Nights are mostly uneventful, and the discipline is in doing the uneventful parts anyway: the rounds happen, the log gets written, the lights go off at the same time every night.",
      ),
      eBlockHeader("Rounds", 2),
      eBlockList("checklist", [
        { content: "Lights out at the posted time, no negotiation, no exceptions for one person" },
        { content: "First round twenty minutes later" },
        { content: "Rounds every two hours until morning" },
        { content: "Kitchen and exits checked on every round" },
        { content: "One line per round in the night log, even when nothing happened" },
      ]),
      eBlockAlert(
        "danger",
        "Never wake the house to resolve one person's problem. Take the conversation to the office, and if it cannot wait until morning, call the lead — that is what the phone is for.",
      ),
      eBlockHeader("The three a.m. conversation", 3),
      eBlockParagraph(
        "Somebody who cannot sleep and finds you in the office at three in the morning is often having the most honest conversation of their whole stay. Do not send them back to bed on principle. Make tea, listen for twenty minutes, and write two lines about it for the day shift — what was said stays between you, that it happened does not.",
      ),
      eBlockHeader("How far to take it: the ladder", 2),
      eBlockImage("escalation-ladder", "Four rungs. Most nights never leave the first one."),
      eBlockParagraph(
        "The ladder is deliberately short. If you are unsure which rung you are on, you are on the next one up — uncertainty at night is itself a reason to call. Nobody has ever been reprimanded here for waking the lead; people have been talked to for not doing it.",
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Handover between shifts",
    title: "Handover between shifts",
    sectionSlug: "night-shift",
    order: 2,
    cardColor: "purple",
    tags: ["night", "communication", "documents"],
    blocks: [
      eBlockParagraph(
        "Fifteen minutes, both consultants in the room, the log open between you. The handover is spoken and written — one without the other does not count.",
      ),
      eBlockHeader("Said out loud, in this order", 2),
      eBlockList("ordered", [
        { content: "Who is in the house and who is not" },
        { content: "Anyone unwell, upset, or newly arrived" },
        { content: "What was promised to whom, and by when" },
        { content: "What broke, ran out, or needs buying" },
        { content: "Anything the next shift must decide" },
      ]),
      eBlockAlert(
        "warning",
        "A handover done through a message is a handover that did not happen. If you truly cannot meet, phone — and write the log yourself, not the other person.",
      ),
      eBlockParagraph(
        `The paper form is ${link("form", "records", "Shift handover log", "Shift handover log")}. The printable summary table below fits a single landscape sheet for the office wall.`,
      ),
    ],
  },

  // --- Film therapy ---------------------------------------------------------
  {
    type: "film",
    nameSlugSource: "Starting over",
    title: "Starting over",
    sectionSlug: "film-therapy",
    order: 1,
    cardColor: "red",
    tags: ["therapy", "programme"],
    video: clip("film-starting-over.mp4", 21.52),
    introBlocks: [
      eBlockParagraph(
        "A quiet story about a man who loses the job that defined him and has to build an ordinary week from nothing. Shown in the second month, when the novelty of the programme has worn off and the work gets boring.",
      ),
      eBlockList("unordered", [
        { content: "Running time: under two hours, one break" },
        { content: "Nothing graphic; safe for a mixed group" },
        { content: "Watch it yourself before the session, even if you have seen it" },
      ]),
    ],
    questionsBlocks: [
      eBlockHeader("Questions for the discussion", 2),
      eBlockList("ordered", [
        { content: "What did he do on the first morning when nothing was scheduled?" },
        { content: "Who did he tell the truth to, and why that person?" },
        { content: "Where in the film did pride cost him something?" },
        { content: "What in his week looks like your week here?" },
      ]),
      eBlockAlert(
        "warning",
        "Let the group answer badly. A discussion where the consultant supplies the right reading teaches nothing except that there is a right reading.",
      ),
    ],
  },
  {
    type: "film",
    nameSlugSource: "The family that waits",
    title: "The family that waits",
    sectionSlug: "film-therapy",
    order: 2,
    cardColor: "pink",
    tags: ["therapy", "communication"],
    video: clip("film-family-that-waits.mp4", 21.52),
    introBlocks: [
      eBlockParagraph(
        "Told from the family's side rather than the resident's. Usually the hardest session of the month, and the one people mention a year later.",
      ),
      eBlockAlert(
        "warning",
        "Warn the group at the start of the week that this film is coming. Nobody should meet it by surprise on a bad day.",
      ),
    ],
    questionsBlocks: [
      eBlockHeader("Questions for the discussion", 2),
      eBlockList("ordered", [
        { content: "Which promise in the film did you recognise?" },
        { content: "What did the family stop believing, and what made them stop?" },
        { content: "What would you want said to you if you were the one waiting?" },
      ]),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Running a film discussion",
    title: "Running a film discussion",
    sectionSlug: "film-therapy",
    order: 3,
    cardColor: "purple",
    tags: ["therapy", "communication"],
    blocks: [
      eBlockParagraph(
        "The film is the easy part. The discussion afterwards is where the session either does its work or turns into an hour of opinions about cinema.",
      ),
      eBlockList("checklist", [
        { content: "Watch the film yourself first, with the questions in front of you" },
        { content: "Start with the plainest question, not the deepest one" },
        { content: "Let silence run — count to ten before filling it" },
        { content: "Close the session, always: nobody leaves the room mid-thought" },
      ]),
      eBlockParagraph(
        `Two sessions are ready to run: ${link("film", "film-therapy", "Starting over", "Starting over")} and ${link("film", "film-therapy", "The family that waits", "The family that waits")}.`,
      ),
    ],
  },

  // --- Group work -----------------------------------------------------------
  {
    type: "article",
    nameSlugSource: "Running a check-in group",
    title: "Running a check-in group",
    sectionSlug: "group-work",
    order: 1,
    cardColor: "purple",
    tags: ["therapy", "communication"],
    blocks: [
      eBlockParagraph(
        "The check-in is the workhorse of group formats: forty minutes, one question, everyone answers it. It looks so simple that new consultants underprepare for it — and then discover that holding a group of twelve people to one honest question is a craft.",
      ),
      eBlockHeader("The frame", 2),
      eBlockList("ordered", [
        { content: "One question, announced at the start and never changed midway" },
        { content: "Speaking order goes around the ring — no volunteering, no picking" },
        { content: "Three minutes a person; the facilitator keeps time openly, not apologetically" },
        { content: "The facilitator answers the question too, last, and briefly" },
      ]),
      eBlockHeader("Questions that work", 3),
      eBlockList("unordered", [
        { content: "“What took the most effort this week?” — effort, not success: everyone has effort" },
        { content: "“What did you almost not say today?” — for a group that has warmed up over months" },
        { content: "“Who here helped you this week, and did they know it?” — builds the habit of noticing" },
      ]),
      eBlockAlert(
        "warning",
        "A question that worked once will die if used weekly. Rotate; keep a private list of what you have already asked and what the room did with it.",
      ),
      eBlockParagraph(
        `When the answers stop coming, resist the urge to fill the air — ${link("article", "group-work", "When the group goes silent", "When the group goes silent")} is about exactly that moment. The slide deck for training new facilitators is ${link("presentation", "group-work", "Running your first group", "Running your first group")}.`,
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "When the group goes silent",
    title: "When the group goes silent",
    sectionSlug: "group-work",
    order: 2,
    cardColor: "blue",
    tags: ["therapy", "communication"],
    blocks: [
      eBlockParagraph(
        "Every facilitator meets the silence. The mistake is treating all silences as the same problem — most of them are not problems at all.",
      ),
      eBlockHeader("Four silences, four responses", 2),
      eBlockTable(true, [
        ["What it looks like", "What it usually is", "What the facilitator does"],
        ["Eyes down, right after a heavy answer", "The room is digesting", "Nothing. Count to twenty, slowly"],
        ["Glances between two people", "Something the group knows and you don't", "Name it gently: “Something is in the room — does it belong here?”"],
        ["Flat faces, third dead question in a row", "The question is wrong or worn out", "Drop it out loud and ask a smaller one"],
        ["One person's silence while the rest talk", "A private matter surfacing", "Let it be; find them after the group, one to one"],
      ]),
      eBlockQuote(
        "Silence in a group is not the absence of the session. Half the time, it is the session.",
        "Staff handbook",
      ),
      eBlockAlert(
        "warning",
        "Never make silence a discipline issue — “we are not leaving until somebody speaks” produces speech and destroys the group, in that order.",
      ),
    ],
  },
  {
    type: "presentation",
    nameSlugSource: "Running your first group",
    title: "Running your first group",
    sectionSlug: "group-work",
    order: 3,
    cardColor: "pink",
    tags: ["therapy", "intake"],
    fileExt: "pptx",
    fileSizeOriginal: 1_680_000,
    fileSizePdf: 520_000,
    fileLines: [
      "Before the room fills: chairs in one ring, question chosen, clock visible",
      "Open the same way every time - ritual lowers the temperature",
      "Your job is the frame, not the content",
      "Three minutes a person, kept openly",
      "Answer your own question last, and briefly",
      "Close on time even mid-sentence: the frame is the therapy",
    ],
  },

  // --- Working with families ------------------------------------------------
  {
    type: "article",
    nameSlugSource: "The first family phone call",
    title: "The first family phone call",
    sectionSlug: "families",
    order: 1,
    cardColor: "green",
    tags: ["communication", "intake"],
    blocks: [
      eBlockParagraph(
        "Within a day or two of an admission, somebody calls: a mother, a wife, a brother. They are frightened, often angry, and they have usually been managing this crisis alone for years. The first call sets the terms for every later one.",
      ),
      eBlockHeader("What the call is for", 2),
      eBlockList("ordered", [
        { content: "Confirm the person arrived and is safe — that is the sentence they called for" },
        { content: "Explain the schedule of calls and visits, with dates, so hope has a shape" },
        { content: "Ask what the family wants staff to know — then listen without defending anyone" },
        { content: "Give one name and one number: theirs to call, not a different person each time" },
      ]),
      eBlockHeader("What not to promise", 3),
      eBlockList("unordered", [
        { content: "Not outcomes — “he will be fine” is not yours to give" },
        { content: "Not reports on what the person says or does — that belongs to them, not the family" },
        { content: "Not exceptions to the visit schedule as a favour — exceptions go through the lead" },
      ]),
      eBlockAlert(
        "danger",
        "Check the intake sheet before dialling or answering: it lists who must not be contacted, and that list outranks any caller's insistence, tears included.",
      ),
      eBlockParagraph(
        `The visit schedule lives in ${link("article", "house-rules", "Phones and visits", "Phones and visits")}; the day itself is described in ${link("article", "families", "Visiting day", "Visiting day")}.`,
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Visiting day",
    title: "Visiting day",
    sectionSlug: "families",
    order: 2,
    cardColor: "blue",
    tags: ["communication", "programme"],
    blocks: [
      eBlockParagraph(
        "Visits are medicine with side effects. Done well, they remind a person what they are working toward; done carelessly, they undo three weeks in an afternoon. Staff run the day with the same quiet structure as everything else.",
      ),
      eBlockHeader("Before, during, after", 2),
      eBlockList("checklist", [
        { content: "The day before: remind the resident, ask how they feel about it — and mean the question" },
        { content: "Visitors sign in; bags stay at the office, gifts go through staff first" },
        { content: "Visits happen in the common room, not in bedrooms — no exceptions" },
        { content: "A consultant stays visible but not hovering: reachable in one glance" },
        { content: "After the goodbye, find the resident within the hour — the hardest part starts when the car leaves" },
      ]),
      eBlockAlert(
        "warning",
        "If a visitor arrives in a state that worries you, the visit does not happen, kindly and without negotiation at the door. Offer to rebook, tell the lead, write it down. The resident is told the truth in plain words.",
      ),
      eBlockParagraph(
        `The signed agreement each visitor reads first is ${link("form", "families", "Family visit agreement", "the family visit agreement")}. What families ask of staff — and where those requests must stop — is covered in ${link("article", "families", "Boundaries with relatives", "Boundaries with relatives")}.`,
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Boundaries with relatives",
    title: "Boundaries with relatives",
    sectionSlug: "families",
    order: 3,
    cardColor: "red",
    tags: ["communication", "regulations"],
    blocks: [
      eBlockParagraph(
        "Families are allies, and allies under stress push. Most of the pushing is love wearing a bad disguise, which is exactly why it is hard to refuse. The boundaries below are refused kindly, refused always, and refused by every consultant identically — a boundary with exceptions is a negotiation.",
      ),
      eBlockHeader("The recurring requests", 2),
      eBlockTable(true, [
        ["The request", "Why it comes", "The answer"],
        ["“Tell me what he says in group”", "Years of being lied to", "“What he says here is his. What I can tell you is how the programme works.”"],
        ["“Just pass her this money”", "Guilt looks for small errands", "Money never moves through staff — it goes to the office, documented"],
        ["“Don't tell him I called”", "Fear of anger", "No secret channels: the resident knows who called, always"],
        ["“You can make an exception once”", "Hope that rules are soft here too", "Exceptions go to the lead, in writing, before the day — not at the door"],
      ]),
      eBlockQuote(
        "Every boundary you hold for a family is a rehearsal of the ones they will need to hold at home.",
        "Staff handbook",
      ),
      eBlockAlert(
        "danger",
        "A consultant who takes money, messages or secrets from a family member has ended their shift — the same line as in “What consultants must not do”, seen from the other side of the fence.",
      ),
    ],
  },
  {
    type: "form",
    nameSlugSource: "Family visit agreement",
    title: "Family visit agreement",
    sectionSlug: "families",
    order: 4,
    cardColor: "neutral",
    tags: ["documents", "communication"],
    fileExt: "pdf",
    fileSizeOriginal: 92_000,
    fileSizePdf: 92_000,
    fileLines: [
      "Visitor name and relationship to the resident",
      "Date and agreed hours of the visit",
      "I agree that bags and gifts are handed to staff on arrival.",
      "I agree that the visit takes place in the common room.",
      "I agree to end the visit if staff ask, without discussion at the door.",
      "Nothing that alters one's state may be brought onto the grounds.",
      "Signature of the visitor / signature of the consultant on duty",
    ],
  },

  // --- Crisis situations ----------------------------------------------------
  {
    type: "article",
    nameSlugSource: "Conflict between residents",
    title: "Conflict between residents",
    sectionSlug: "crisis",
    order: 1,
    cardColor: "red",
    tags: ["crisis", "communication"],
    video: clip("conflict-first-minutes.mp4", 22.52),
    blocks: [
      eBlockAlert(
        "danger",
        "First three minutes: separate, do not adjudicate. Nothing you say while both are shouting will be remembered by either of them.",
      ),
      eBlockHeader("What you do, in order", 2),
      eBlockList("ordered", [
        { content: "Put yourself between them and take the volume down by lowering your own voice" },
        { content: "Send them to different rooms with a task each" },
        { content: "Ask the room what happened before you ask either of them" },
        { content: "Talk to each one alone, the calmer one first" },
        { content: "Bring them together only when both can say what the other wanted" },
      ]),
      eBlockHeader("What makes it worse", 3),
      eBlockList("unordered", [
        { content: "Deciding who started it in front of an audience" },
        { content: "Any promise you cannot keep by tonight" },
        { content: "Involving the whole house in a matter between two people" },
      ]),
      eBlockParagraph(
        `Everything above goes into the incident report the same shift — ${link("form", "crisis", "Incident report", "Incident report")}.`,
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "A resident wants to leave",
    title: "A resident wants to leave",
    sectionSlug: "crisis",
    order: 2,
    cardColor: "red",
    tags: ["crisis", "communication"],
    blocks: [
      eBlockParagraph(
        "People are here voluntarily, and the door is not locked. Your job is not to prevent them from leaving; it is to make sure the decision is made awake, fed, and in daylight if that is at all possible.",
      ),
      eBlockList("ordered", [
        { content: "Sit down with them — literally, both of you seated" },
        { content: "Ask what happened in the last two hours" },
        { content: "Offer tea, food, sleep: most of it passes with any one of the three" },
        { content: "If they still intend to go, call the lead while they gather their things" },
        { content: "Return belongings by the inventory, without argument" },
        { content: "Say plainly that they can come back, and mean it" },
      ]),
      eBlockAlert(
        "danger",
        "Never block a doorway, take a phone, or hold on to documents to keep someone in the building. It is unsafe, it destroys the trust of everyone watching, and it is not what this place is.",
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Suspected relapse",
    title: "Suspected relapse",
    sectionSlug: "crisis",
    order: 3,
    cardColor: "red",
    tags: ["crisis", "therapy"],
    blocks: [
      eBlockParagraph(
        "A suspicion is not a verdict, and the first conversation decides whether the person tells you the truth this time and next time.",
      ),
      eBlockList("checklist", [
        { content: "Do not confront in front of the group" },
        { content: "Do not search anyone's belongings alone" },
        { content: "Tell the lead before you tell anybody else" },
        { content: "Ask directly and once, then be quiet and listen" },
        { content: "Write what you observed, not what you concluded" },
      ]),
      eBlockQuote(
        "Recovery is not a straight line, and a relapse handled with dignity is the reason someone comes back at all.",
        "Staff handbook",
      ),
      eBlockAlert(
        "warning",
        "If the person seems unwell rather than intoxicated, treat it as a medical situation first and sort out the rest afterwards.",
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Medical emergency",
    title: "Medical emergency",
    sectionSlug: "crisis",
    order: 4,
    cardColor: "red",
    tags: ["crisis"],
    blocks: [
      eBlockAlert(
        "danger",
        "Call the emergency number first. Everything else on this page happens while you wait, not before you call.",
      ),
      eBlockList("ordered", [
        { content: "Call, and say the address before anything else" },
        { content: "Send someone to the gate to meet them" },
        { content: "Stay with the person; do not move them unless they are in danger where they lie" },
        { content: "Clear the room of everyone who is not helping" },
        { content: "Call the lead" },
        { content: "Write the incident report while the details are exact" },
      ]),
      eBlockParagraph(
        "Staff give first aid only within what they are trained and certified to do, and never medication of any kind.",
      ),
    ],
  },
  {
    type: "form",
    nameSlugSource: "Incident report",
    title: "Incident report",
    sectionSlug: "crisis",
    order: 5,
    cardColor: "neutral",
    tags: ["documents", "crisis"],
    fileExt: "docx",
    fileSizeOriginal: 37_000,
    fileSizePdf: 74_000,
    fileLines: [
      "Date and time of the incident",
      "Who was present",
      "What happened, in order, observed only",
      "What the consultant did",
      "Who was informed, and when",
      "Follow-up agreed with the lead",
      "Signature of the consultant on duty",
    ],
  },
  {
    type: "presentation",
    nameSlugSource: "De-escalation basics",
    title: "De-escalation basics",
    sectionSlug: "crisis",
    order: 6,
    cardColor: "blue",
    tags: ["crisis", "communication"],
    fileExt: "pptx",
    fileSizeOriginal: 2_100_000,
    fileSizePdf: 610_000,
    fileLines: [
      "Lower your voice before you raise your argument",
      "Separate the people first, discuss later",
      "One consultant speaks at a time",
      "Give a task, not an ultimatum",
      "Write the incident report the same shift",
    ],
  },

  // --- Journals and forms ---------------------------------------------------
  {
    type: "article",
    nameSlugSource: "Why we keep journals",
    title: "Why we keep journals",
    sectionSlug: "records",
    order: 1,
    cardColor: "green",
    tags: ["documents", "regulations"],
    blocks: [
      eBlockParagraph(
        "Journals are not for inspectors. They are for the consultant who comes on shift in six hours and needs to know what happened without waking anyone up to ask.",
      ),
      eBlockList("unordered", [
        { content: "Written the same shift, not reconstructed the next morning" },
        { content: "Facts and observations; conclusions belong in the conversation with the lead" },
        { content: "Names of residents kept to what the entry actually needs" },
        { content: "Signed, because an unsigned entry cannot be asked about" },
      ]),
      eBlockQuote("Write the line you would want to find if you were arriving tired at ten at night.", "Staff handbook"),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Filling journals without drowning in paper",
    title: "Filling journals without drowning in paper",
    sectionSlug: "records",
    order: 2,
    cardColor: "blue",
    tags: ["documents", "chores"],
    blocks: [
      eBlockParagraph(
        "Four journals is already a lot. The trick is that each has exactly one question it answers, and no entry belongs in two of them.",
      ),
      eBlockTable(true, [
        ["Journal", "Answers", "Filled by", "When"],
        ["Night log", "Did the rounds happen and what did they find?", "Night consultant", "Every round"],
        ["Handover", "What must the next shift know?", "Both consultants", "At every changeover"],
        ["Food register", "Was the meal fit to serve?", "Duty consultant", "Before each meal"],
        ["Incidents", "What happened that was out of the ordinary?", "Whoever was there", "Same shift"],
      ]),
      eBlockAlert(
        "warning",
        "If you find yourself writing the same sentence into two journals, one of the two entries is in the wrong place.",
      ),
      eBlockParagraph(
        `The reasoning behind all of it is in ${link("article", "records", "Why we keep journals", "Why we keep journals")}.`,
      ),
    ],
  },
  {
    type: "form",
    nameSlugSource: "Daily journal page",
    title: "Daily journal page",
    sectionSlug: "records",
    order: 3,
    cardColor: "neutral",
    tags: ["documents", "therapy"],
    fileExt: "docx",
    fileSizeOriginal: 28_000,
    fileSizePdf: 61_000,
    fileLines: [
      "Date and time",
      "What happened today",
      "What I felt, in one word",
      "What I did with it",
      "What I will do differently tomorrow",
      "Signature",
    ],
  },
  {
    type: "form",
    nameSlugSource: "Shift handover log",
    title: "Shift handover log",
    sectionSlug: "records",
    order: 4,
    cardColor: "neutral",
    tags: ["documents", "night"],
    fileExt: "xlsx",
    fileSizeOriginal: 54_000,
    fileSizePdf: 88_000,
    fileLines: [
      "Date, shift handed over at",
      "Who is in the house, who is away",
      "Anyone unwell or upset",
      "Promises made, and by when",
      "What broke or ran out",
      "Decisions left to the next shift",
      "Handed over by / accepted by",
    ],
  },
  {
    type: "form",
    nameSlugSource: "Food quality register",
    title: "Food quality register",
    sectionSlug: "records",
    order: 5,
    cardColor: "neutral",
    tags: ["documents", "chores"],
    fileExt: "xlsx",
    fileSizeOriginal: 47_000,
    fileSizePdf: 79_000,
    fileLines: [
      "Date and meal",
      "Dish tasted",
      "Temperature acceptable: yes / no",
      "Portion size against headcount",
      "Fit to serve: yes / no",
      "Signature of the duty consultant",
    ],
  },
  {
    type: "form",
    nameSlugSource: "Fridge temperature log",
    title: "Fridge temperature log",
    sectionSlug: "records",
    order: 6,
    cardColor: "neutral",
    tags: ["documents", "chores"],
    fileExt: "xlsx",
    fileSizeOriginal: 39_000,
    fileSizePdf: 66_000,
    fileLines: [
      "Date and time of reading",
      "Fridge number",
      "Temperature recorded",
      "Within range: yes / no",
      "Action taken if out of range",
      "Signature",
    ],
  },

  // --- House rules ----------------------------------------------------------
  {
    type: "article",
    nameSlugSource: "House rules in one page",
    title: "House rules in one page",
    sectionSlug: "house-rules",
    order: 1,
    cardColor: "green",
    tags: ["regulations", "communication"],
    blocks: [
      eBlockParagraph(
        "Read together with every newcomer on the second day, signed once, and posted where everyone can point at it.",
      ),
      eBlockList("checklist", [
        { content: "Nothing that alters your state comes through the door" },
        { content: "No violence and no threats, in any direction" },
        { content: "Everyone is at the circle, at meals, and at group" },
        { content: "Chores are done by the person whose name is on the rota" },
        { content: "Phones and visits by the posted schedule" },
        { content: "Lights out is lights out" },
      ]),
      eBlockParagraph(
        `The limits on the staff side are in ${link("article", "house-rules", "What consultants must not do", "What consultants must not do")}.`,
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Phones and visits",
    title: "Phones and visits",
    sectionSlug: "house-rules",
    order: 2,
    cardColor: "blue",
    tags: ["regulations", "communication"],
    blocks: [
      eBlockParagraph(
        "The rule exists to protect the first weeks, not to punish anyone. It relaxes as the programme goes on, and the schedule is posted so nobody has to ask a favour.",
      ),
      eBlockTable(true, [
        ["Week", "Calls", "Visits"],
        ["1–2", "One call, staff present", "None"],
        ["3–4", "Two calls a week", "One visit, in the common room"],
        ["From week 5", "Daily, at posted hours", "Weekends"],
      ]),
      eBlockAlert(
        "warning",
        "Exceptions are made by the lead, not by the duty consultant, and are written into the handover so the next shift is not ambushed.",
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "What consultants must not do",
    title: "What consultants must not do",
    sectionSlug: "house-rules",
    order: 3,
    cardColor: "red",
    tags: ["regulations", "crisis"],
    blocks: [
      eBlockAlert(
        "danger",
        "These are not preferences. Any one of them ends the shift immediately and is discussed with the lead the same day.",
      ),
      eBlockList("unordered", [
        { content: "Lending or borrowing money, from anyone, for any reason" },
        { content: "Any relationship with a resident beyond the working one" },
        { content: "Bringing anything through the door that residents may not have" },
        { content: "Discussing one resident with another" },
        { content: "Giving medication, or advice that sounds like a prescription" },
        { content: "Working a shift while unwell enough to need to sit down" },
      ]),
      eBlockParagraph(
        "The point of the list is that it removes judgement calls from moments when judgement is tired.",
      ),
    ],
  },
  {
    type: "presentation",
    nameSlugSource: "Rules for the first week",
    title: "Rules for the first week",
    sectionSlug: "house-rules",
    order: 4,
    cardColor: "pink",
    tags: ["regulations", "intake"],
    fileExt: "ppt",
    fileSizeOriginal: 890_000,
    fileSizePdf: 310_000,
    fileLines: [
      "Week one: what is expected of you",
      "Lights out and the daily timetable",
      "Calls and visits in the first two weeks",
      "Chores: how the rota works",
      "Who to talk to if a rule feels unfair",
    ],
  },

  // --- Aftercare ------------------------------------------------------------
  {
    type: "article",
    nameSlugSource: "Transitional housing",
    title: "Transitional housing",
    sectionSlug: "aftercare",
    order: 1,
    cardColor: "green",
    tags: ["aftercare", "programme"],
    blocks: [
      eBlockParagraph(
        "The transitional flat is the rehearsal: same structure, fewer walls. People pay their share, cook for themselves, and keep one evening a week here.",
      ),
      eBlockList("ordered", [
        { content: "Work or study during the day, verified by nobody — but discussed weekly" },
        { content: "Own money, own shopping, own mistakes" },
        { content: "One group evening a week, non-negotiable" },
        { content: "A call to the consultant when something slips, before it becomes a week" },
      ]),
      eBlockParagraph(
        `What the weekly conversation covers is in ${link("article", "aftercare", "Aftercare check-ins", "Aftercare check-ins")}.`,
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "Aftercare check-ins",
    title: "Aftercare check-ins",
    sectionSlug: "aftercare",
    order: 2,
    cardColor: "blue",
    tags: ["aftercare", "communication"],
    blocks: [
      eBlockParagraph(
        "Twenty minutes a week, same day, same time. The regularity is the intervention: a call that happens only when things are bad becomes a call nobody makes.",
      ),
      eBlockList("unordered", [
        { content: "Sleep, food, money — in that order, every time" },
        { content: "Who they spoke to this week outside work" },
        { content: "What is scheduled for next week that they are dreading" },
        { content: "One thing that went well, said out loud" },
      ]),
      eBlockQuote("The needs at the bottom of the pyramid go wrong first, and they go wrong quietly.", "Staff handbook"),
    ],
  },
  {
    type: "article",
    nameSlugSource: "The first month back at work",
    title: "The first month back at work",
    sectionSlug: "aftercare",
    order: 3,
    cardColor: "purple",
    tags: ["aftercare", "communication"],
    blocks: [
      eBlockParagraph(
        "A job brings money, structure and a new set of ways to be exhausted. The first month is planned in advance, not improvised on the first bad Friday.",
      ),
      eBlockList("checklist", [
        { content: "Decide in advance who at work, if anyone, is told what" },
        { content: "Write down the hour of the day that is likely to be hardest" },
        { content: "Plan the route home that does not pass the old places" },
        { content: "Keep the weekly check-in even during a good month" },
      ]),
      eBlockAlert(
        "warning",
        "A month of overtime in week one is not commitment, it is the same pattern in a shirt. Say so early, kindly, and more than once.",
      ),
    ],
  },
  {
    type: "article",
    nameSlugSource: "The call nobody wants to make",
    title: "The call nobody wants to make",
    sectionSlug: "aftercare",
    order: 4,
    cardColor: "red",
    tags: ["aftercare", "crisis"],
    blocks: [
      eBlockParagraph(
        "Sooner or later a graduate calls — or their family does — and the news is bad. How the consultant takes that call decides whether it is the end of the story or the middle of it.",
      ),
      eBlockHeader("On the phone", 2),
      eBlockList("ordered", [
        { content: "Thank them for calling. Out loud, first sentence — the call took more courage than the slip" },
        { content: "Ask about today: are they safe, where are they, who is with them" },
        { content: "No inquest. When and how it started can wait for a table and two cups of tea" },
        { content: "Offer something concrete with a time on it: come by on Thursday, call again at eight" },
        { content: "Tell the lead the same day; write two lines in the journal" },
      ]),
      eBlockHeader("What to say when there is nothing to say", 3),
      eBlockParagraph(
        "“I am glad you called. This is a thing that happens on the way, not the end of the way. You know where we are, and the door has not moved.” It is nearly a formula, and that is fine — a person in that moment does not need originality, they need to hear that the floor is still there.",
      ),
      eBlockQuote(
        "A relapse ends a stretch of recovery. It only ends recovery if nobody picks up the phone.",
        "Staff handbook",
      ),
      eBlockParagraph(
        `Inside the walls, the same situation is governed by ${link("article", "crisis", "Suspected relapse", "Suspected relapse")}; the weekly rhythm that makes this call less likely is in ${link("article", "aftercare", "Aftercare check-ins", "Aftercare check-ins")}.`,
      ),
    ],
  },
];
